"""users table

Revision ID: 557a6080c6ad
Revises: 
Create Date: 2019-02-02 11:22:20.393093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557a6080c6ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('net_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=75), nullable=True),
    sa.Column('last_name', sa.String(length=75), nullable=True),
    sa.Column('school_name', sa.String(length=75), nullable=True),
    sa.Column('program_name', sa.String(length=75), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_net_user_email'), 'net_user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_net_user_email'), table_name='net_user')
    op.drop_table('net_user')
    # ### end Alembic commands ###
